### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by JulStraus** [EnergyModelsX/EnergyModelsBase.jl#17]
The current change in the examples allow to run these from a version of `EnergyModelsBase` included from the registry through [PR14](https://github.com/EnergyModelsX/EnergyModelsBase.jl/pull/14). However, a problem now arises for testing the examples. In practice, the tests no longer utilize the version that is the latest, but instead the latest version from the Registry. When testing locally, this problem does not occur, but when testing on GitHub, that can become a problem.

Hence, we should find a solution with the following properties:

- It still allows to run the examples directly from the file (including instantiation of the corresponding package) and
- The tests are testing the latest version of the package.

Thoughts?

**Comment by hellemo** [comment]
Two options that come to mind are:
1. add `Manifest.toml` with a relative path reference to the parent folder
2. develop the package if checked out for developmen or in CI, see https://github.com/EnergyModelsX/EnergyModelsBase.jl/pull/33 for an attempt to do this

**Comment by JulStraus** [comment]
Point 1 would definitely work, although it would require minor changes in the `.gitignore` file.

Point 2 is a bit more interesting to check out. In practice, we cannot test whether it works except if we have it registered. Otherwise, we will never run in the potential problem that there is no possibility for overriding in a folder we do not have the right to override. I checked that out with a local version in which I called the functions for running the examples. In this situation, the problem was that is also used `develop` when calling it from a different environment as `@__DIR__ = \EnergyModelsBase.jl\examples` within the file.

**Comment by hellemo** [comment]
When exactly do we want to run with the development version? I assume for CI and when we are running tests locally for new versions?

One alternative could be to use an explicit flag to turn this on, e.g. like 
```julia
if haskey(ENV, "EMB_TEST_OR_CI")
    @info "only for test or CI"
end
```
and set the appropriate environment variable as part of the tests, but will not be run by default.

**Comment by JulStraus** [comment]
After testing the directory of an added package, I think it can work:

``` julia
julia> using EnergyModelsBase

julia> exdir = joinpath(pkgdir(EnergyModelsBase), "examples")
"\\.julia\\packages\\EnergyModelsBase\\XtYXL\\examples"
```

as it does not include the .jl ending, when added.
