### ISSUE TITLE
Consider dropping `texttt` for variables

### ISSUE THREAD

**Issue by hellemo** [EnergyModelsX/EnergyModelsBase.jl#20]
variables annotated with ```\texttt`` are not so nice in the documentation view from the REPL, consider switching to "`" (backticks):

![image](https://github.com/EnergyModelsX/EnergyModelsBase.jl/assets/1584698/10f87df2-8270-4465-a118-3c3123b6d4e8)

**Comment by JulStraus** [comment]
I agree, that this is a bit unfortunate. It would be nice to have the LaTeX description for the documentation as it allows us to differentiate between variables in Julia and variables of the optimization problem. However, I see the issue in using the help mode in the REPL.
