### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by odow** [EnergyModelsX/EnergyModelsBase.jl#21]
x-ref https://github.com/openjournals/joss-reviews/issues/6619

## Checklist items

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

You could add a paragraph to the documentation, or a CONTRIBUTING.md file.

> References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)?

I would add:
 * https://github.com/GenXProject/GenX.jl
 * https://github.com/TulipaEnergy/TulipaEnergyModel.jl

## Other

 - [x] I think the paper would benefit from a pretty picture or an example. I don't have any concrete suggestion, but could you make a figure with a plot of input time series and an output of various dispatch/cost/flows, etc?
 - [x] https://github.com/EnergyModelsX/EnergyModelsGeography.jl/pull/15

**Comment by JulStraus** [comment]
First of all, thanks for agreeing to review the paper. We are currently working on incorporating the individual comments:

1.  The individual links in the different packages were updated to not point towards internal gitlab pages.
2. We added a contribution section to the documentation of `EnergyModelsBase`. Once this is accepted, we will update the other packages correspondingly.
3. We will look into the references and update the list accordingly.

@hellemo and I are currently discussing a potential figure, as we agree that it can improve the paper. We are however uncertain, whether a results figure is what we aim for in this paper. We will however update the paper soon with a figure.

**Comment by odow** [comment]
> whether a results figure is what we aim for in this paper

Yeah I understand. I guess something more indicative of what this is/could be used for. Currently, the paper is fairly abstract in the sense "you can use it to build things" but "you can use it to build a model of hydrogen generation and transshipments in Scandinavia with wind uncertainty" is much more concrete. Dunno. Just a pretty picture.

**Comment by hellemo** [comment]
Thanks for reviewing our submission, @odow !

As mentioned above, @JulStraus has updated the documentation with a new sections addressing contributions.

We have also updated the paper manuscript now with the following changes:
1. Added references to GenX and Tulipa
2. Added a figure with an example application (hydrogen infrastructure development in the North Sea)
3. Fixed the flagged DOI
4. Fixed the URL for link to SINTEF

**Comment by odow** [comment]
Just one other comment, you might want to add another citation to Bodal in the "Example application" section. It's currently just in the summary.

**Comment by hellemo** [comment]
Just updated with the following addition: 

"See also @bodal2024hydrogen for a similar example."

The reason we didn't add it first was because the figure is from a separate study (in preparation), but they share many  properties in terms of modelling.
