### ISSUE TITLE
Clarification of multiple-function

### ISSUE THREAD

**Issue by espenfb** [EnergyModelsX/EnergyModelsBase.jl#40]
The function multiple(t_inv, t) have several versions (in both TimeStruct and EnergyModelsBase) that are easy to mix up when implementing new technologies. The function is exported from TimeStruct, but not from EnergyModelsBase, while it is the version from EnergyModelsBase one would want for implementing new technologies. Changing the name of the multiple-function in EnergyModelsBase might help to aviod mistakes in the future.

**Comment by JulStraus** [comment]
I agree. The question is how we call the new function. It is quite closely related to the functionality from `TimeStruct`, that is why I called it that way, but then again, it can lead to problems if not approached careful. It is also interesting, that `TimeStruct` uses the function `multiple` with two inputs only 3 times, a default function, as well as for `StratReprPeriod` and `StratNodeReprPeriod`. The latter was implemented by me as a copy of the former. What is your take on this @trulsf ?

**Comment by trulsf** [comment]
I think the  `multiple` function with two inputs could be considered removed in the next version of `TimeStruct`. I have never actively used it, and it should be possible to get the required information using `mult_strat`, `mult_repr`and `mult_scen` as appropriate. If one wants to have the option of having this two input function for strategic periods, one could define   
`
multiple(sp::AbstractStrategicPeriod, t) = mutiple(t) / mult_strat(sp)
`
